### ISSUE TITLE
Missing AWS.SAMLCredentials

### ISSUE THREAD

**Issue by davidhouweling** [ingenieux/aws-sdk-typescript#17]
Referring to the AWS Documentation: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SAMLCredentials.html#constructor_details

I'm attempting to set `AWS.config.credentials = new AWS.SAMLCredentials({ ... })` but doesn't seem like its been accounted for.

**Comment by aldrinleal** [comment]
Basically my work on this repo has been reduced to using grep :)

```
aldrin@aldrin-X555LD aws-sdk-typescript $ grep -Ri saml output/typings/*.d.ts
output/typings/aws-iam.d.ts:     * Creates an IAM entity to describe an identity provider (IdP) that supports SAML
output/typings/aws-iam.d.ts:The SAML provider that you create with this operation can be used as a principal
output/typings/aws-iam.d.ts:SAML identity provider. You can create an IAM role that supports Web-based
output/typings/aws-iam.d.ts:When you create the SAML provider, you upload an a SAML metadata document that
output/typings/aws-iam.d.ts:information, and keys that can be used to validate the SAML authentication
output/typings/aws-iam.d.ts:more information, see Enabling SAML 2.0 Federated Users to Access the AWS
output/typings/aws-iam.d.ts:[http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-saml.html] 
output/typings/aws-iam.d.ts:and About SAML 2.0-based Federation
output/typings/aws-iam.d.ts:[http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html] 
output/typings/aws-iam.d.ts:    createSAMLProvider(params: IAM.CreateSAMLProviderRequest, callback?: (err: IAM.InvalidInputException | IAM.EntityAlreadyExistsException | IAM.LimitExceededException | IAM.ServiceFailureException | any, data: IAM.CreateSAMLProviderResponse | any) => void): Request<IAM.CreateSAMLProviderResponse | any, IAM.InvalidInputException | IAM.EntityAlreadyExistsException | IAM.LimitExceededException | IAM.ServiceFailureException | any>;
output/typings/aws-iam.d.ts:     * Deletes a SAML provider.
output/typings/aws-iam.d.ts:Deleting the provider does not update any roles that reference the SAML provider
output/typings/aws-iam.d.ts:references a SAML provider that has been deleted will fail.
output/typings/aws-iam.d.ts:    deleteSAMLProvider(params: IAM.DeleteSAMLProviderRequest, callback?: (err: IAM.InvalidInputException | IAM.LimitExceededException | IAM.NoSuchEntityException | IAM.ServiceFailureException | any, data: any) => void): Request<any, IAM.InvalidInputException | IAM.LimitExceededException | IAM.NoSuchEntityException | IAM.ServiceFailureException | any>;
output/typings/aws-iam.d.ts:     * Returns the SAML provider metadocument that was uploaded when the provider was
output/typings/aws-iam.d.ts:    getSAMLProvider(params: IAM.GetSAMLProviderRequest, callback?: (err: IAM.NoSuchEntityException | IAM.InvalidInputException | IAM.ServiceFailureException | any, data: IAM.GetSAMLProviderResponse | any) => void): Request<IAM.GetSAMLProviderResponse | any, IAM.NoSuchEntityException | IAM.InvalidInputException | IAM.ServiceFailureException | any>;
output/typings/aws-iam.d.ts:     * Lists the SAML providers in the account.
output/typings/aws-iam.d.ts:    listSAMLProviders(params: IAM.ListSAMLProvidersRequest, callback?: (err: IAM.ServiceFailureException | any, data: IAM.ListSAMLProvidersResponse | any) => void): Request<IAM.ListSAMLProvidersResponse | any, IAM.ServiceFailureException | any>;
output/typings/aws-iam.d.ts:     * Updates the metadata document for an existing SAML provider.
output/typings/aws-iam.d.ts:    updateSAMLProvider(params: IAM.UpdateSAMLProviderRequest, callback?: (err: IAM.NoSuchEntityException | IAM.InvalidInputException | IAM.LimitExceededException | IAM.ServiceFailureException | any, data: IAM.UpdateSAMLProviderResponse | any) => void): Request<IAM.UpdateSAMLProviderResponse | any, IAM.NoSuchEntityException | IAM.InvalidInputException | IAM.LimitExceededException | IAM.ServiceFailureException | any>;
output/typings/aws-iam.d.ts:    export type SAMLMetadataDocumentType = string;
output/typings/aws-iam.d.ts:    export type SAMLProviderListType = SAMLProviderListEntry[];
output/typings/aws-iam.d.ts:    export type SAMLProviderNameType = string;
output/typings/aws-iam.d.ts:    export interface CreateSAMLProviderRequest {
output/typings/aws-iam.d.ts:      /** An XML document generated by an identity provider (IdP) that supports SAML 2.0.
output/typings/aws-iam.d.ts:can be used to validate the SAML authentication response (assertions) that are
output/typings/aws-iam.d.ts:For more information, see About SAML 2.0-based Federation
output/typings/aws-iam.d.ts:[http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html] 
output/typings/aws-iam.d.ts:      SAMLMetadataDocument: SAMLMetadataDocumentType;
output/typings/aws-iam.d.ts:      Name: SAMLProviderNameType;
output/typings/aws-iam.d.ts:    export interface CreateSAMLProviderResponse {
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider. **/
output/typings/aws-iam.d.ts:      SAMLProviderArn?: arnType;
output/typings/aws-iam.d.ts:    export interface DeleteSAMLProviderRequest {
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider to delete. **/
output/typings/aws-iam.d.ts:      SAMLProviderArn: arnType;
output/typings/aws-iam.d.ts:    export interface GetSAMLProviderRequest {
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider to get information about. **/
output/typings/aws-iam.d.ts:      SAMLProviderArn: arnType;
output/typings/aws-iam.d.ts:    export interface GetSAMLProviderResponse {
output/typings/aws-iam.d.ts:      SAMLMetadataDocument?: SAMLMetadataDocumentType;
output/typings/aws-iam.d.ts:      /** The date and time when the SAML provider was created. **/
output/typings/aws-iam.d.ts:      /** The expiration date and time for the SAML provider. **/
output/typings/aws-iam.d.ts:    export interface ListSAMLProvidersRequest {
output/typings/aws-iam.d.ts:    export interface ListSAMLProvidersResponse {
output/typings/aws-iam.d.ts:      /** The list of SAML providers for this account. **/
output/typings/aws-iam.d.ts:      SAMLProviderList?: SAMLProviderListType;
output/typings/aws-iam.d.ts:    export interface SAMLProviderListEntry {
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider. **/
output/typings/aws-iam.d.ts:      /** The expiration date and time for the SAML provider. **/
output/typings/aws-iam.d.ts:      /** The date and time when the SAML provider was created. **/
output/typings/aws-iam.d.ts:    export interface UpdateSAMLProviderRequest {
output/typings/aws-iam.d.ts:      /** An XML document generated by an identity provider (IdP) that supports SAML 2.0.
output/typings/aws-iam.d.ts:can be used to validate the SAML authentication response (assertions) that are
output/typings/aws-iam.d.ts:      SAMLMetadataDocument: SAMLMetadataDocumentType;
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider to update. **/
output/typings/aws-iam.d.ts:      SAMLProviderArn: arnType;
output/typings/aws-iam.d.ts:    export interface UpdateSAMLProviderResponse {
output/typings/aws-iam.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider that was updated. **/
output/typings/aws-iam.d.ts:      SAMLProviderArn?: arnType;
output/typings/aws-sts.d.ts:Permissions for AssumeRole, AssumeRoleWithSAML, and AssumeRoleWithWebIdentity
output/typings/aws-sts.d.ts:authenticated via a SAML authentication response. This operation provides a
output/typings/aws-sts.d.ts:AssumeRoleWithSAML with the other APIs that produce temporary credentials, see 
output/typings/aws-sts.d.ts:when calling AssumeRole , or until the time specified in the SAML authentication
output/typings/aws-sts.d.ts:The temporary security credentials created by AssumeRoleWithSAML can be used to
output/typings/aws-sts.d.ts:Permissions for AssumeRole, AssumeRoleWithSAML, and AssumeRoleWithWebIdentity
output/typings/aws-sts.d.ts:Before your application can call AssumeRoleWithSAML , you must configure your
output/typings/aws-sts.d.ts:SAML identity provider (IdP) to issue the claims required by AWS. Additionally,
output/typings/aws-sts.d.ts:you must use AWS Identity and Access Management (IAM) to create a SAML provider
output/typings/aws-sts.d.ts:IAM role that specifies this SAML provider in its trust policy.
output/typings/aws-sts.d.ts:Calling AssumeRoleWithSAML does not require the use of AWS security credentials.
output/typings/aws-sts.d.ts:that is uploaded for the SAML provider entity for your identity provider.
output/typings/aws-sts.d.ts:Calling AssumeRoleWithSAML can result in an entry in your AWS CloudTrail logs.
output/typings/aws-sts.d.ts:The entry includes the value in the NameID element of the SAML assertion. We
output/typings/aws-sts.d.ts:Persistent Identifier ( urn:oasis:names:tc:SAML:2.0:nameid-format:persistent ).
output/typings/aws-sts.d.ts: &amp;#42; About SAML 2.0-based Federation
output/typings/aws-sts.d.ts:   [http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html] 
output/typings/aws-sts.d.ts: * Creating SAML Identity Providers
output/typings/aws-sts.d.ts:   [http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml.html] 
output/typings/aws-sts.d.ts:   [http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_relying-party.html] 
output/typings/aws-sts.d.ts: * Creating a Role for SAML 2.0 Federation
output/typings/aws-sts.d.ts:   [http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_saml.html] 
output/typings/aws-sts.d.ts:    assumeRoleWithSAML(params: STS.AssumeRoleWithSAMLRequest, callback?: (err: STS.MalformedPolicyDocumentException | STS.PackedPolicyTooLargeException | STS.IDPRejectedClaimException | STS.InvalidIdentityTokenException | STS.ExpiredTokenException | STS.RegionDisabledException | any, data: STS.AssumeRoleWithSAMLResponse | any) => void): Request<STS.AssumeRoleWithSAMLResponse | any, STS.MalformedPolicyDocumentException | STS.PackedPolicyTooLargeException | STS.IDPRejectedClaimException | STS.InvalidIdentityTokenException | STS.ExpiredTokenException | STS.RegionDisabledException | any>;
output/typings/aws-sts.d.ts:Permissions for AssumeRole, AssumeRoleWithSAML, and AssumeRoleWithWebIdentity
output/typings/aws-sts.d.ts:    assumeRoleWithSAML(...args: any[]): any
output/typings/aws-sts.d.ts:    export type SAMLAssertionType = string;
output/typings/aws-sts.d.ts:information, see Permissions for AssumeRole, AssumeRoleWithSAML, and
output/typings/aws-sts.d.ts:    export interface AssumeRoleWithSAMLRequest {
output/typings/aws-sts.d.ts:      /** The Amazon Resource Name (ARN) of the SAML provider in IAM that describes the
output/typings/aws-sts.d.ts:      /** The base-64 encoded SAML authentication response provided by the IdP.
output/typings/aws-sts.d.ts:[http://docs.aws.amazon.com/IAM/latest/UserGuide/create-role-saml-IdP-tasks.html] 
output/typings/aws-sts.d.ts:      SAMLAssertion: SAMLAssertionType;
output/typings/aws-sts.d.ts:AssumeRole, AssumeRoleWithSAML, and AssumeRoleWithWebIdentity
output/typings/aws-sts.d.ts:3600 seconds. An expiration can also be specified in the SAML authentication
output/typings/aws-sts.d.ts:    export interface AssumeRoleWithSAMLResponse {
output/typings/aws-sts.d.ts:      /** The value of the NameID element in the Subject element of the SAML assertion. **/
output/typings/aws-sts.d.ts:element of the SAML assertion. Typical examples of the format are transient or 
output/typings/aws-sts.d.ts:If the format includes the prefix urn:oasis:names:tc:SAML:2.0:nameid-format ,
output/typings/aws-sts.d.ts:urn:oasis:names:tc:SAML:2.0:nameid-format:transient is returned as transient .
output/typings/aws-sts.d.ts:      /** The value of the Issuer element of the SAML assertion. **/
output/typings/aws-sts.d.ts:the SAML assertion. **/
output/typings/aws-sts.d.ts:account ID, and the friendly name (the last part of the ARN) of the SAML
output/typings/aws-sts.d.ts:BASE64 ( SHA1 ( &quot;https://example.com/saml&quot; + &quot;123456789012&quot; + &quot;/MySAMLIdP&quot; ) ) **/
```

**Comment by aldrinleal** [comment]
Err, this is one of the "special cases". You're welcome to write the binding manually and submit a patch. Likely you'll need to tweak the `app/src/aws-sdk.handlebars` file.

**Comment by davidhouweling** [comment]
Unfortunately I cannot seem to get the build to compile locally (on Windows 10 running in Git Bash).

``` console
machine@machine MINGW64 /c/github/aws-sdk-typescript (master)
$ npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> aws-sdk-typescript@ prepublish C:\github\aws-sdk-typescript
> gulp buildrun && npm run-script format

[06:51:35] Using gulpfile C:\github\aws-sdk-typescript\gulpfile.js
[06:51:35] Starting 'clean:generated'...
[06:51:35] Starting 'clean:build'...
[06:51:35] Finished 'clean:generated' after 9.35 ms
[06:51:35] Finished 'clean:build' after 14 ms
[06:51:35] Starting 'clean'...
[06:51:35] Finished 'clean' after 32 μs
[06:51:35] Starting 'compile:typescript'...
app\src\app.ts(1,1): error TS6053: File 'C:/github/aws-sdk-typescript/typings/main.d.ts' not found.
app\src\app.ts(5,21): error TS2307: Cannot find module 'fs'.
app\src\app.ts(6,23): error TS2307: Cannot find module 'path'.
app\src\app.ts(7,23): error TS2307: Cannot find module 'glob'.
app\src\app.ts(9,15): error TS2304: Cannot find name 'require'.
app\src\app.ts(11,26): error TS2307: Cannot find module 'esprima'.
app\src\app.ts(13,18): error TS2304: Cannot find name 'require'.
app\src\app.ts(15,17): error TS2304: Cannot find name 'require'.
app\src\app.ts(17,29): error TS2307: Cannot find module 'handlebars'.
app\src\app.ts(20,1): error TS2304: Cannot find name 'require'.
app\src\app.ts(62,41): error TS2304: Cannot find name '__dirname'.
app\src\app.ts(98,41): error TS2304: Cannot find name '__dirname'.
app\src\app.ts(195,28): error TS2304: Cannot find name 'process'.
app\src\generator.ts(1,1): error TS6053: File 'C:/github/aws-sdk-typescript/typings/main.d.ts' not found.
app\src\generator.ts(4,21): error TS2307: Cannot find module 'fs'.
app\src\generator.ts(5,29): error TS2307: Cannot find module 'handlebars'.
app\src\generator.ts(6,29): error TS2307: Cannot find module 'html-to-text'.
app\src\generator.ts(42,42): error TS2304: Cannot find name '__dirname'.
[06:51:36] TypeScript: 18 semantic errors
[06:51:36] TypeScript: emit succeeded (with errors)
[06:51:36] Finished 'compile:typescript' after 1.28 s
[06:51:36] Starting 'build'...
[06:51:36] Finished 'build' after 11 μs
[06:51:36] Starting 'run'...
["C:\\Program Files\\nodejs\\node.exe","C:\\github\\aws-sdk-typescript\\node_modules\\gulp-cli\\bin\\gulp.js","buildrun"]
[06:51:37] 'run' errored after 230 ms
[06:51:37] Error: ENOENT: no such file or directory, open 'C:\github\aws-sdk-typescript\aws-sdk-js\apis\metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at readMetadata (C:\source\app.ts:26:24)
    at Object.<anonymous> (C:\source\app.ts:199:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DavidHou\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! aws-sdk-typescript@ prepublish: `gulp buildrun && npm run-script format`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-sdk-typescript@ prepublish script 'gulp buildrun && npm run-script format'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-sdk-typescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp buildrun && npm run-script format
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-sdk-typescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-sdk-typescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\github\aws-sdk-typescript\npm-debug.log

machine@machine MINGW64 /c/github/aws-sdk-typescript (master)
$
```

**Comment by aldrinleal** [comment]
try this - its what on Continuous Integration currently:

``` shell
npm install typescript typings gulp gulp-cli
./node_modules/.bin/typings install
npm install
npm run-script test
```

**Comment by davidhouweling** [comment]
I decided to give up on Typescript as AWS sdk is vital for the project I'm on and not wanting to run into other issues, just found it easier to shift the project back to babel. I guess you can either leave this open for someone else to pick up, or close it and wait for someone else to raise it?

**Comment by pentode** [comment]
FWIW, I was able to get this built by installing the aws-sdk and then copying it into aws-sdk-js...

```
npm install typescript typings gulp gulp-cli
./node_modules/.bin/typings install
npm install aws-sdk
cp node_modules/aws-sdk/* aws-sdk-js/
npm run-script test
```

**Comment by davidhouweling** [comment]
shouldn't those libraries all be listed as dev dependencies? As much as they suggest having them as globals, it should not be assumed that everyone does, and it is fine to list each as a dev dependency.

Also, seems very odd to copy `aws-sdk` to `aws-sdk-js`...

**Comment by aldrinleal** [comment]
thats due to us using git submodules (here's a [tutorial on how to use it](https://github.com/NebuPookins/git-submodule-tutorial))

The reason is that it only matters to have the latest, up to date AWS SDK installed, so our build environment uses it via submodules to read the jsons and generate the needed stubs.

notice the build also regenerates and uploads its content. the reason is to make simpler for users using typings to simply download the relevant repo contents (output/typings) and get stuff done (notice the commit log to get an idea on how often the AWS SDK for JS is updated)
